import "bootstrap";
import "devise/sign_up";
import "../components/navbar";
import "../components/search";
import "../components/stats";
import "movies/mark_as_like";
import "movies/mark_as_dislike";
import "movies/mark_as_save";
import "movies/mark_as_blacklist";
import "components/step_two"
import "components/spinwheel"
